name: bluesky_2020_9
channels:
  - defaults
  - conda-forge
  - aps-anl-tag
  - nsls2forge
  - pydm-tag
  - pcds-tag
dependencies:
  - python>=3.7
  - aps-dm-api
  - apstools
  - area-detector-handlers
  - bluesky>=1.6.2
  - databroker>=1.0.6
  - h5py
  - happi
  - hklpy
  - imagecodecs-lite
  - ipython
  - jupyter
  - jupyterlab
  - lxml
  - notebook
  - ophyd>=1.5.1
  - pandoc
  - pint
  - pip
  - psutil
  - punx
  - pvview
  - pydm
  - pyEpics>=3.4.2
  - pygobject
  - pylint
  - pymongo
  - pyqt=5
  - pyRestTable
  - qt=5
  - scikit-image
  - spec2nexus
  - sphinx
  - stdlogpj
  - typhos
  - versioneer
  - xlrd
  - pip:
    - ipython-genutils==0.2.0
    - sphinx-rtd-theme
    - super-state-machine
