name: bluesky_2021_2
channels:
  - defaults
  - conda-forge
  - nsls2forge
  - aps-anl-tag
dependencies:
  # - anaconda
  # --- Python core packages
  - python>=3.8
  - ipython
  - jupyter
  - jupyterlab
  - notebook
  - pip
  - psutil
  # --- testing and quality assurance
  - black
  - flake8
  - pylint
  - pytest
  # --- Qt
  - pyqt=5
  - qt=5
  # --- support packages
  - h5py
  - imagecodecs-lite
  - ipympl
  - lxml
  - pandas
  - pint
  - pymongo
  - scikit-image
  - xlrd
  # --- Bluesky framework packages
  - aps-dm-api
  - apstools
  - area-detector-handlers
  - bluesky>=1.6.7
  - bluesky-widgets 
  - databroker-pack
  - databroker>=1.2.3
  - epics-base>=7.0.5
  - happi
  - hklpy>=0.3.16
  - ophyd>=1.6.1
  - pydm
  - pyEpics>=3.4.3
  # --- user-requested packages
  - nexpy
  - punx
  - pvview
  - pymca
  - pyRestTable
  - spec2nexus
  - stdlogpj
  - xrayutilities
  # --- packaging and publishing
  - conda-build
  - coverage
  - sphinx
  - sphinxcontrib-napoleon
  - twine
  - versioneer
  # pip not needed now: all packages included from above
  # - pip:
  #   # - sphinx-rtd-theme
  #   - super-state-machine
